# Sample workflow to access AWS resources when workflow is tied to branch
# The workflow creates a static website using Amazon S3
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: AWS example workflow
on: push
env:
  AWS_REGION: "eu-west-1"
# permission can be added at job level or workflow level
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v5
      - uses: jdx/mise-action@v3
        with:
          install: true
          cache: true
          log_level: debug
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: arn:aws:iam::005097939719:role/ci-terraform
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}
      - name: Check credentials by getting caller identity
        run: |
          aws sts get-caller-identity
      - name: Check credentials by getting caller identity
        run: |
          tofu --version
